services:
  pytorch:
    build: .
    devices:
    - /dev/nvidia0
    - /dev/nvidia1
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    - /dev/nvidia-uvm-tools
    environment:
    - PYTHONIOENCODING=utf_8
    ipc: host
    volumes:
    - .:/app
    - /etc/localtime:/etc/localtime:ro
    - nvidia_driver_375.51:/usr/local/nvidia:ro
version: '2'
volumes:
  nvidia_driver_375.51:
    external: true
